### PR TITLE
Improve monorepo support

### PR DESCRIPTION
**Pull request by sjahu**
real author: @mkevinosullivan

I'm creating this draft PR to discuss these proposed changes before we create a PR against the upstream branch (this way we can avoid pinging lokalize until we're happy with changes on our side).

Technically, we can comment directly on a commit, but then any discussion is basically impossible to find if further changes are made on the branch that overwrite the commit.

> Update abstract class PackageParser to look for the given package file in each folder of a given root directory. This allows for a deep scan to find potential frameworks that need to be supported.

### CODE REVIEW

**Review by sjahu — COMMENTED** [review]
Nice change! I tested it and it appears to work on our test project.

I have two concerns with this approach, however (both from cursory inspection of the code-- if I'm missing something about how it actually works in practice, let me know).

Thoughts on whether these are legit problems or whether this behaviour would be acceptable?

**Loads all dependencies together**

The `load` method returns a list of the dependencies specified in a `package.json`, `Gemfile`, etc file. Originally, it looked for this file only in the root of the workspace. Now, it'll traverse the entire subtree.

Problem: all the dependencies are returned together in a combined array. If you have multiple sub-projects using the same package system, this could be an issue for detecting the correct framework.

E.g.

```
/foo
  package.json (contains `react-i18next`)
/bar
  package.json (contains `shopify-i18next`)
/baz
  package.json (contains `fluent-vue`)
```

All of these dependencies will be included in the list returned by this method; how does the extension choose which one to actually use for picking frameworks? (possible answer: I believe it tries to use all of them, and enables all associated frameworks... unless the `monopoly` property happens to be enabled for one).

**Enables parent framework for child project**
Similarly, what if you have the following setup:

```
/foo
  package.json (contains `react-i18next`)
package.json (contains `fluent-vue`)
```

Now will both the `react-i18next` and `fluent-vue` frameworks be enabled everywhere?

**Comment by mkevinosullivan** [comment]
> Nice change! I tested it and it appears to work on our test project.
> 
> I have two concerns with this approach, however (both from cursory inspection of the code-- if I'm missing something about how it actually works in practice, let me know).
> 
> Thoughts on whether these are legit problems or whether this behaviour would be acceptable?
> 
> **Loads all dependencies together**
> 
> The `load` method returns a list of the dependencies specified in a `package.json`, `Gemfile`, etc file. Originally, it looked for this file only in the root of the workspace. Now, it'll traverse the entire subtree.
> 
> Problem: all the dependencies are returned together in a combined array. If you have multiple sub-projects using the same package system, this could be an issue for detecting the correct framework.
> 
> E.g.
> 
> ```
> /foo
>   package.json (contains `react-i18next`)
> /bar
>   package.json (contains `shopify-i18next`)
> /baz
>   package.json (contains `fluent-vue`)
> ```
> 
> All of these dependencies will be included in the list returned by this method; how does the extension choose which one to actually use for picking frameworks? (possible answer: I believe it tries to use all of them, and enables all associated frameworks... unless the `monopoly` property happens to be enabled for one).
> 
> **Enables parent framework for child project** Similarly, what if you have the following setup:
> 
> ```
> /foo
>   package.json (contains `react-i18next`)
> package.json (contains `fluent-vue`)
> ```
> 
> Now will both the `react-i18next` and `fluent-vue` frameworks be enabled everywhere?

Yes, this could very well be a problem (thinking of a monorepo like `quilt`, which has 70+ packages within it!). Similarly, for large monorepos, with lots of locale files within it, it could become a bit of a memory sink.

I'll take another look at doing this dynamically per file activation in editor (if a new file is now active, check for the applicable package file, reload iff different from what's currently loaded)

**Review by Precha24 — COMMENTED** [review]
Good thk

**Comment by trishrempel** [comment]
Closing this PR, as we've taken a different approach that doesn't require monorepo support.

**Pull request closed without merging**
